camunda.bpm.admin-user:
  id: demo
  password: demo

server:
  port: 21470
  servlet:
    context-path: /
    session:
      timeout: 600s

activemq:
  broker:
    url: tcp://localhost:61616

spring:
  #  h2:
  #    console.enabled: true
  #    console:
  #      path: /h2-console
  #      settings.trace: false
  #      settings.web-allow-others: false
  datasource:
    url: jdbc:postgresql://localhost:5432/blps
    username: postgres
    password: qwerty
    #    driverClassName: org.h2.Driver
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss


app:
  jwtSecret: secret_key

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings